Update Agreement Concept with additional attributes
accordproject/apap pull request #7
Opened 2023-01-18 22:23 UTC by martinhalford

Signed-off-by: Martin Halford <martin@benext.io>

Add properties/attributes to Agreement Concept in order to better support instantiation of agreements. 

This includes:
- Parties
- State
- History
- Signatures
- Attachments/References
- Metadata

This PR is intended to be a work-in-progress / draft proposal / starting-point upon which to iterate.

2023-01-24 14:31 UTC, dselman commented on model/protocol.cto
> +import org.accordproject.party.* from https://models.accordproject.org/accordproject/party.cto
Should use an explicit (no '*') versioned import.

2023-01-24 14:31 UTC, dselman commented on model/protocol.cto
> +    o History[] history                     // History of document state and details.
optional?

2023-01-24 14:32 UTC, dselman commented on model/protocol.cto
> +    o String[] metaData optional            // Geolocation data, IP address, etc.
differs in case "metaData" from rest.

2023-01-24 14:32 UTC, dselman commented on model/protocol.cto
> +    o String[] metadata optional            // Additional data that may be relevant to the agreement at time of change
3x instances of metadata - perhaps this should be a concept?

2023-01-24 14:32 UTC, dselman requested changes
Nice!

2023-01-25 05:15 UTC, martinhalford commented on model/protocol.cto
> +import org.accordproject.party.* from https://models.accordproject.org/accordproject/party.cto
OK. Setting to `import org.accordproject.party@0.2.0.*`

2023-01-25 05:25 UTC, martinhalford commented on model/protocol.cto
> +    o History[] history                     // History of document state and details.
As `agreementParties`, `signatures`, and `history` are all arrays, and can be empty, then I thought it would be safer & simpler to make them mandatory.  All agreement instances will, ultimately, have `agreementParties`, `signatures`, and some `history`- therefore, not wasted space.

As for `agreementStatus`, I was thinking that any agreement instance must have a status - either `Draft`, `Signing`, `Completed` or `Superseded` - so, personally, think this should be mandatory.  If we come across a use case that is not handled by these 4 status types then we can add it (e.g `None` could be an enum).

2023-01-25 05:39 UTC, martinhalford commented on model/protocol.cto
> +    o History[] history                     // History of document state and details.
Based on this logic, I've removed `optional` from other arrays in the bits I added.  Must admit, `optional` fields have caused me pain in the past - so tend to use them only when I have to. :-)

2023-01-25 05:45 UTC, martinhalford commented on model/protocol.cto
> +    o String[] metadata optional            // Additional data that may be relevant to the agreement at time of change
We could do but it felt like overkill for a single data field - it's just a data bucket at the moment.

If this needs to become more complicated, say, with multiple named fields and data types then we should def. make it a concept.

2023-01-25 05:50 UTC, martinhalford commented on model/protocol.cto
> +    o String[] metaData optional            // Geolocation data, IP address, etc.
Have standardised on camel case.

2023-01-25 12:44 UTC, merged